--- #YAML:1.0
name:               Acme-24
version:            0.03
abstract:           Your favourite TV-show Acme module
author:
    - Cosimo Streppone <cosimo@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    LWP::Simple:   0
    XML::RSSLite:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.47_01
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
